import Head from "next/head";

// Components
import Checkout from "@/modules/checkout";

// Types
import type { NextPage, GetServerSideProps } from "next";

export const getServerSideProps: GetServerSideProps = async (context) => {
  const subdomain = context.req.headers.host?.split(".")[0];

  console.log(subdomain);

  return {
    props: {},
  };
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Agotao</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <Checkout />
    </>
  );
};

export default Home;
