packages:
  - apps/web
  - apps/papi
  - apps/checkout
  - apps/admin
  - packages/api
  - packages/db
  - packages/config/*
  - packages/validations
  - packages/emails
  - packages/firebase-admin
  - packages/utils
